"""
Django settings for rpg project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import inspect

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p$s%8@^0n38iz!dz^*2)yxd&eg_s_!9@fxkn1o$ua2kb8t^=7-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'drf_spectacular',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rpg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rpg.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rpg_educacional_db',
        'USER': 'root',
        'PASSWORD': 'admin',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'RPG Educacional API',
    'DESCRIPTION': inspect.cleandoc
    (""" ## API REST Polimórfica para Gamificação de Disciplinas
    ### 1. CONTA
    * `POST /api/conta/` - Salvar (Cria uma nova conta).
    * `GET /api/conta/` - Consultar Todos.
    * `GET /api/conta/<id>/` - Consultar por ID.
    * `PUT /api/conta/<id>/` - Alterar conta existente.
    * `DELETE /api/conta/<id>/` - Deletar conta.
    * `POST /api/conta/login/` - Realizar Login (Valida email e senha).

    ### 2. PESSOA
    * `POST /api/pessoa/` - Salvar (Cria uma nova pessoa).
    * `GET /api/pessoa/` - Consultar Todos.
    * `GET /api/pessoa/<id>/` - Consultar por ID.
    * `PUT /api/pessoa/<id>/` - Alterar pessoa.
    * `DELETE /api/pessoa/<id>/` - Deletar pessoa.

    ### 3. ALUNO
    * `POST /api/aluno/` - Salvar (Cria um novo aluno).
    * `GET /api/aluno/` - Consultar Todos.
    * `GET /api/aluno/<id>/` - Consultar por ID.
    * `PUT /api/aluno/<id>/` - Alterar aluno.
    * `DELETE /api/aluno/<id>/` - Deletar aluno.
    * `POST /api/aluno/comprar/` - Comprar Item (Desconta moedas e associa item).

    ### 4. PROFESSOR
    * `POST /api/professor/` - Salvar (Cria um novo professor).
    * `GET /api/professor/` - Consultar Todos.
    * `GET /api/professor/<id>/` - Consultar por ID.
    * `PUT /api/professor/<id>/` - Alterar professor.
    * `DELETE /api/professor/<id>/` - Deletar professor.

    ### 5. PERSONAGEM
    * `POST /api/personagem/` - Salvar (Cria um novo personagem).
    * `GET /api/personagem/` - Consultar Todos.
    * `GET /api/personagem/<id>/` - Consultar por ID.
    * `PUT /api/personagem/<id>/` - Alterar personagem (ex: customizar avatar).
    * `DELETE /api/personagem/<id>/` - Deletar personagem.

    ### 6. DISCIPLINA
    * `POST /api/disciplina/` - Salvar (Cria uma nova disciplina).
    * `GET /api/disciplina/` - Consultar Todos.
    * `GET /api/disciplina/<id>/` - Consultar por ID.
    * `PUT /api/disciplina/<id>/` - Alterar disciplina.
    * `DELETE /api/disciplina/<id>/` - Deletar disciplina.
    * `POST /api/disciplina/matricular/` - Matricular Aluno.

    ### 7. QUESTS
    * `POST /api/quests/` - Salvar (Cria uma nova quest).
    * `GET /api/quests/` - Consultar Todos.
    * `GET /api/quests/<id>/` - Consultar por ID.
    * `PUT /api/quests/<id>/` - Alterar quest.
    * `DELETE /api/quests/<id>/` - Deletar quest.
    * `POST /api/quests/responder/` - Responder Quest (Valida a resposta do aluno).

    ### 8. ITEM
    * `POST /api/item/` - Salvar (Cria um novo item na loja).
    * `GET /api/item/` - Consultar Todos.
    * `GET /api/item/<id>/` - Consultar por ID.
    * `PUT /api/item/<id>/` - Alterar item.
    * `DELETE /api/item/<id>/` - Deletar item.
    """),

    
    
}
