# Generated by Django 6.0.6 on 2026-06-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pessoa_conta_delete_raid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='titulacao',
        ),
        migrations.AddField(
            model_name='conta',
            name='tipo_conta',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=20),
        ),
    ]
