# Generated by Django 6.0.6 on 2026-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_aluno_matricula_remove_professor_titulacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='alternativa_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quests',
            name='alternativa_b',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quests',
            name='alternativa_c',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quests',
            name='alternativa_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quests',
            name='resposta_correta',
            field=models.CharField(max_length=1),
        ),
    ]
