# Generated by Django 6.0.6 on 2026-06-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quests_alternativa_a_quests_alternativa_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='recompensa',
            field=models.IntegerField(default=50),
        ),
    ]
