# Generated by Django 6.0.6 on 2026-06-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quests_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='itens',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='api.item'),
        ),
    ]
